server:
  port: 8082
eureka: 
  client: 
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl: 
       defaultZone: http://localhost:8089/eureka/
#       defaultZone: http://192.168.0.113:8089/eureka/
spring:
#  refresh:
#    refreshable: none
  application: 
    name: boss-service
  datasource: 
    url: jdbc:mysql://localhost:3306/reptiledatabase?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  configuration:
   #配置项：开启下划线到驼峰的自动转换. 作用：将数据库字段根据驼峰规则自动注入到对象属性。
   map-underscore-to-camel-case: true
   
#  mapperLocations: classpath:mapper/*.xml



ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
  eureka:
    enable: true

feign:
  client:
    default:
      #这里时间一定要调长，否则feign客户端会报ReadTimeOut  服务端报Error parsing HTTP request header
      connectTimeout: 60000
      readTimeout: 60000
      loggerLevel: basic