server:
  port: 8082
eureka: 
  client: 
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl: 
      defaultZone: http://localhost:8089/eureka/
spring:
  application: 
    name: boss-service