server:
  port: 8099

spring:
  application: 
    name: proup-web
  datasource: 
    url: jdbc:mysql://localhost:3306/reptiledatabase?allowMultiQueries=true&useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

eureka: 
  client: 
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl: 
       defaultZone: http://localhost:8089/eureka/
#       defaultZone: http://192.168.0.113:8089/eureka/
    
ribbon:
  eureka:
    enabled: true

feign:
  client:
    default:
      #这里时间一定要调长，否则feign客户端会报ReadTimeOut  服务端报Error parsing HTTP request header
      connectTimeout: 30000
      readTimeout: 30000
      loggerLevel: basic