server:
  port: 8081

spring:
  application: 
    name: project-web


eureka: 
  client: 
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl: 
      defaultZone: http://localhost:8089/eureka/
#       defaultZone: http://192.168.0.113:8089/eureka/
    
ribbon:
  eureka:
    enabled: true
    