server:
  port: 8081

spring:
  application: 
    name: project-web
  redis:
     database: 0
     host: 127.0.0.1
     port: 6379
     timeout: 30000
#    cluster: 
#         nodes: 
#         maxRedirects:
     pool:
        max-active: 8
        min-idle: 0
        max-idle: 8
        max-wait: -1

eureka: 
  client: 
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl: 
      defaultZone: http://localhost:8089/eureka/
#       defaultZone: http://192.168.0.113:8089/eureka/
    
ribbon:
  eureka:
    enabled: true
    